=== anineco/gpx2jsgi/iconlut.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT iconlut (icon*)>
<!ELEMENT icon (#PCDATA)>
<!ATTLIST icon code CDATA #REQUIRED
               size CDATA #REQUIRED
               src  CDATA #REQUIRED>

=== anineco/gpx2jsgi/iconlut.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="iconlut2html.xsl"?>
<!DOCTYPE iconlut SYSTEM "iconlut.dtd" [
<!ENTITY baseurl "https://map.jpn.org/icon/">
]>
<iconlut>
<icon code="901001" src="&baseurl;901001.png" size="24">ピン</icon>
<icon code="901002" src="&baseurl;901002.png" size="24">ポイント</icon>
<icon code="902001" src="&baseurl;902001.png" size="24">記号</icon>
<icon code="902002" src="&baseurl;902002.png" size="24">記号</icon>
<icon code="902003" src="&baseurl;902003.png" size="24">記号</icon>
<icon code="902004" src="&baseurl;902004.png" size="24">記号</icon>
<icon code="902005" src="&baseurl;902005.png" size="24">記号</icon>
<icon code="902006" src="&baseurl;902006.png" size="24">記号</icon>
<icon code="902007" src="&baseurl;902007.png" size="24">記号</icon>
<icon code="902008" src="&baseurl;902008.png" size="24">記号</icon>
<icon code="902009" src="&baseurl;902009.png" size="24">記号</icon>
<icon code="902010" src="&baseurl;902010.png" size="24">記号</icon>
<icon code="902011" src="&baseurl;902011.png" size="24">記号</icon>
<icon code="902012" src="&baseurl;902012.png" size="24">記号</icon>
<icon code="902013" src="&baseurl;902013.png" size="24">記号</icon>
<icon code="902014" src="&baseurl;902014.png" size="24">記号</icon>
<icon code="902015" src="&baseurl;902015.png" size="24">記号</icon>
<icon code="902016" src="&baseurl;902016.png" size="24">記号</icon>
<icon code="902017" src="&baseurl;902017.png" size="24">記号</icon>
<icon code="902018" src="&baseurl;902018.png" size="24">記号</icon>
<icon code="902019" src="&baseurl;902019.png" size="24">記号</icon>
<icon code="902020" src="&baseurl;902020.png" size="24">記号</icon>
<icon code="902021" src="&baseurl;902021.png" size="24">記号</icon>
<icon code="902022" src="&baseurl;902022.png" size="24">記号</icon>
<icon code="902023" src="&baseurl;902023.png" size="24">記号</icon>
<icon code="902024" src="&baseurl;902024.png" size="24">記号</icon>
<icon code="902025" src="&baseurl;902025.png" size="24">記号</icon>
<icon code="902026" src="&baseurl;902026.png" size="24">記号</icon>
<icon code="902027" src="&baseurl;902027.png" size="24">記号</icon>
<icon code="902028" src="&baseurl;902028.png" size="24">記号</icon>
<icon code="902029" src="&baseurl;902029.png" size="24">記号</icon>
<icon code="902030" src="&baseurl;902030.png" size="24">記号</icon>
<icon code="902031" src="&baseurl;902031.png" size="24">記号</icon>
<icon code="902032" src="&baseurl;902032.png" size="24">記号</icon>
<icon code="902033" src="&baseurl;902033.png" size="24">記号</icon>
<icon code="902034" src="&baseurl;902034.png" size="24">記号</icon>
<icon code="902035" src="&baseurl;902035.png" size="24">記号</icon>
<icon code="902036" src="&baseurl;902036.png" size="24">記号</icon>
<icon code="902037" src="&baseurl;902037.png" size="24">記号</icon>
<icon code="902038" src="&baseurl;902038.png" size="24">記号</icon>
<icon code="902039" src="&baseurl;902039.png" size="24">記号</icon>
<icon code="903001" src="&baseurl;903001.png" size="24">なし</icon>
<icon code="903002" src="&baseurl;903002.png" size="24">アイコン</icon>
<icon code="903003" src="&baseurl;903003.png" size="24">アイコン</icon>
<icon code="903004" src="&baseurl;903004.png" size="24">アイコン</icon>
<icon code="903005" src="&baseurl;903005.png" size="24">アイコン</icon>
<icon code="903006" src="&baseurl;903006.png" size="24">アイコン</icon>
<icon code="903007" src="&baseurl;903007.png" size="24">アイコン</icon>
<icon code="903008" src="&baseurl;903008.png" size="24">アイコン</icon>
<icon code="903009" src="&baseurl;903009.png" size="24">アイコン</icon>
<icon code="903010" src="&baseurl;903010.png" size="24">アイコン</icon>
<icon code="903011" src="&baseurl;903011.png" size="24">アイコン</icon>
<icon code="903012" src="&baseurl;903012.png" size="24">アイコン</icon>
<icon code="903013" src="&baseurl;903013.png" size="24">アイコン</icon>
<icon code="903014" src="&baseurl;903014.png" size="24">アイコン</icon>
<icon code="903015" src="&baseurl;903015.png" size="24">アイコン</icon>
<icon code="903016" src="&baseurl;903016.png" size="24">アイコン</icon>
<icon code="903017" src="&baseurl;903017.png" size="24">アイコン</icon>
<icon code="903018" src="&baseurl;903018.png" size="24">アイコン</icon>
<icon code="903019" src="&baseurl;903019.png" size="24">アイコン</icon>
<icon code="903020" src="&baseurl;903020.png" size="24">アイコン</icon>
<icon code="903021" src="&baseurl;903021.png" size="24">アイコン</icon>
<icon code="903022" src="&baseurl;903022.png" size="24">アイコン</icon>
<icon code="903023" src="&baseurl;903023.png" size="24">アイコン</icon>
<icon code="903024" src="&baseurl;903024.png" size="24">アイコン</icon>
<icon code="903025" src="&baseurl;903025.png" size="24">アイコン</icon>
<icon code="903026" src="&baseurl;903026.png" size="24">アイコン</icon>
<icon code="903027" src="&baseurl;903027.png" size="24">アイコン</icon>
<icon code="903028" src="&baseurl;903028.png" size="24">アイコン</icon>
<icon code="903029" src="&baseurl;903029.png" size="24">アイコン</icon>
<icon code="903030" src="&baseurl;903030.png" size="24">アイコン</icon>
<icon code="903031" src="&baseurl;903031.png" size="24">アイコン</icon>
<icon code="903032" src="&baseurl;903032.png" size="24">アイコン</icon>
<icon code="903033" src="&baseurl;903033.png" size="24">アイコン</icon>
<icon code="903034" src="&baseurl;903034.png" size="24">アイコン</icon>
<icon code="903035" src="&baseurl;903035.png" size="24">アイコン</icon>
<icon code="903036" src="&baseurl;903036.png" size="24">アイコン</icon>
<icon code="903037" src="&baseurl;903037.png" size="24">アイコン</icon>
<icon code="903038" src="&baseurl;903038.png" size="24">アイコン</icon>
<icon code="903039" src="&baseurl;903039.png" size="24">アイコン</icon>
<icon code="903040" src="&baseurl;903040.png" size="24">アイコン</icon>
<icon code="903041" src="&baseurl;903041.png" size="24">アイコン</icon>
<icon code="903042" src="&baseurl;903042.png" size="24">アイコン</icon>
<icon code="903043" src="&baseurl;903043.png" size="24">アイコン</icon>
<icon code="903044" src="&baseurl;903044.png" size="24">アイコン</icon>
<icon code="903045" src="&baseurl;903045.png" size="24">アイコン</icon>
<icon code="903046" src="&baseurl;903046.png" size="24">アイコン</icon>
<icon code="903047" src="&baseurl;903047.png" size="24">アイコン</icon>
<icon code="903048" src="&baseurl;903048.png" size="24">アイコン</icon>
<icon code="903049" src="&baseurl;903049.png" size="24">アイコン</icon>
<icon code="903050" src="&baseurl;903050.png" size="24">アイコン</icon>
<icon code="903051" src="&baseurl;903051.png" size="24">アイコン</icon>
<icon code="903052" src="&baseurl;903052.png" size="24">アイコン</icon>
<icon code="903053" src="&baseurl;903053.png" size="24">アイコン</icon>
<icon code="903054" src="&baseurl;903054.png" size="24">アイコン</icon>
<icon code="903055" src="&baseurl;903055.png" size="24">アイコン</icon>
<icon code="903056" src="&baseurl;903056.png" size="24">アイコン</icon>
<icon code="903057" src="&baseurl;903057.png" size="24">アイコン</icon>
<icon code="903058" src="&baseurl;903058.png" size="24">アイコン</icon>
<icon code="903059" src="&baseurl;903059.png" size="24">アイコン</icon>
<icon code="903060" src="&baseurl;903060.png" size="24">アイコン</icon>
<icon code="903061" src="&baseurl;903061.png" size="24">アイコン</icon>
<icon code="903062" src="&baseurl;903062.png" size="24">アイコン</icon>
<icon code="903063" src="&baseurl;903063.png" size="24">アイコン</icon>
<icon code="903064" src="&baseurl;903064.png" size="24">アイコン</icon>
<icon code="903065" src="&baseurl;903065.png" size="24">アイコン</icon>
<icon code="903066" src="&baseurl;903066.png" size="24">アイコン</icon>
<icon code="903067" src="&baseurl;903067.png" size="24">アイコン</icon>
<icon code="903068" src="&baseurl;903068.png" size="24">アイコン</icon>
<icon code="903069" src="&baseurl;903069.png" size="24">アイコン</icon>
<icon code="903070" src="&baseurl;903070.png" size="24">アイコン</icon>
<icon code="903071" src="&baseurl;903071.png" size="24">アイコン</icon>
<icon code="903072" src="&baseurl;903072.png" size="24">アイコン</icon>
<icon code="903073" src="&baseurl;903073.png" size="24">アイコン</icon>
<icon code="903074" src="&baseurl;903074.png" size="24">アイコン</icon>
<icon code="903075" src="&baseurl;903075.png" size="24">アイコン</icon>
<icon code="903076" src="&baseurl;903076.png" size="24">アイコン</icon>
<icon code="903077" src="&baseurl;903077.png" size="24">アイコン</icon>
<icon code="903078" src="&baseurl;903078.png" size="24">アイコン</icon>
<icon code="903079" src="&baseurl;903079.png" size="24">アイコン</icon>
<icon code="903080" src="&baseurl;903080.png" size="24">アイコン</icon>
<icon code="903081" src="&baseurl;903081.png" size="24">アイコン</icon>
<icon code="903082" src="&baseurl;903082.png" size="24">アイコン</icon>
<icon code="903083" src="&baseurl;903083.png" size="24">アイコン</icon>
<icon code="903084" src="&baseurl;903084.png" size="24">アイコン</icon>
<icon code="903085" src="&baseurl;903085.png" size="24">アイコン</icon>
<icon code="903086" src="&baseurl;903086.png" size="24">アイコン</icon>
<icon code="909001" src="&baseurl;909001.png" size="24">[GPS] Waypoint</icon>
<icon code="909002" src="&baseurl;909002.png" size="24">[GPS] Residence</icon>
<icon code="909003" src="&baseurl;909003.png" size="24">[GPS] Gas Station</icon>
<icon code="909004" src="&baseurl;909004.png" size="24">[GPS] Car</icon>
<icon code="909005" src="&baseurl;909005.png" size="24">[GPS] Fishing Area</icon>
<icon code="909006" src="&baseurl;909006.png" size="24">[GPS] Boat Ramp</icon>
<icon code="909007" src="&baseurl;909007.png" size="24">[GPS] Anchor</icon>
<icon code="909008" src="&baseurl;909008.png" size="24">[GPS] Shipwreck</icon>
<icon code="909009" src="&baseurl;909009.png" size="24">[GPS] </icon>
<icon code="909010" src="&baseurl;909010.png" size="24">[GPS] Danger Area</icon>
<icon code="909011" src="&baseurl;909011.png" size="24">[GPS] Flag</icon>
<icon code="909012" src="&baseurl;909012.png" size="24">[GPS] Campground</icon>
<icon code="909013" src="&baseurl;909013.png" size="24">[GPS] </icon>
<icon code="909014" src="&baseurl;909014.png" size="24">[GPS] Hunting Area</icon>
<icon code="909015" src="&baseurl;909015.png" size="24">[GPS] Medical Facility</icon>
